---
EnableDefaultLinters: true
linters:
  ErbSafety:
    enabled: true
  FinalNewline:
    enabled: true
  SpaceAroundErbTag:
    enabled: true
  SelfClosingTag:
    enabled: true
    enforced_style: 'always'
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
