services:
  - type: web
    name: k-bus-norikae-app
    env: docker
    dockerfilePath: ./docker/Dockerfile.production
    dockerCommand: bundle exec rails server
    plan: Free
    branch: change-heroku-to-render
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false
