services:
  - type: web
    name: web
    env: docker
    dockerfilePath: ./Dockerfile
    dockerCommand: sh start.sh
    plan: Free
    branch: add_active_csv
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false
