services:
  - type: web
    name: k-bus-norikae-app
    env: docker
    dockerfilePath: ./docker/Dockerfile.production
    dockerCommand: sh start_production.sh
    plan: Free
    branch: add_bootstrap
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false
