FROM ruby:3.1

RUN mkdir /rails_app
WORKDIR /rails_app
COPY Gemfile /rails_app/Gemfile
COPY Gemfile.lock /rails_app/Gemfile.lock
RUN bundle install
COPY . /rails_app

COPY start.sh /usr/bin/
RUN chmod a+x /usr/bin/start.sh
EXPOSE 3000
CMD [ "sh", "start.sh" ]
