FROM ruby:3.1

RUN mkdir /rails_app
WORKDIR /rails_app
COPY Gemfile /rails_app/Gemfile
COPY Gemfile.lock /rails_app/Gemfile.lock
RUN bundle install
RUN apt-get update && apt-get -y install vim
COPY . /rails_app

COPY start_production.sh /usr/bin/
RUN chmod a+x /usr/bin/start_production.sh
EXPOSE 3001
# RUN bundle exec rails db:create db:migrate RAILS_ENV=production
CMD [ "sh", "start_production.sh" ]
