FROM ruby:3.1

RUN mkdir /rails_app
WORKDIR /rails_app
COPY Gemfile /rails_app/Gemfile
COPY Gemfile.lock /rails_app/Gemfile.lock
RUN bundle install
# RUN apt-get update && apt-get -y install vim
COPY . /rails_app

COPY start_production.sh /usr/bin/
RUN chmod a+x /usr/bin/start_production.sh
EXPOSE 3000

ENTRYPOINT [ "sh", "start_production.sh" ]
CMD [ "bundle", "exec", "rails", "server", "-b", "0.0.0.0" ]
