FROM ruby:3.1.2-buster

RUN gem install bundler:2.3.26
RUN gem install nokogiri --platform=ruby
RUN bundle config set force_ruby_platform true

RUN mkdir /rails_app
WORKDIR /rails_app
COPY Gemfile /rails_app/Gemfile
COPY Gemfile.lock /rails_app/Gemfile.lock
RUN bundle _2.3.26_ install
COPY . /rails_app

COPY start_dev.sh /usr/bin/
RUN chmod a+x /usr/bin/start_dev.sh
EXPOSE 3000

CMD [ "sh", "start_production.sh" ]
