# https://github.com/AkhileshNS/heroku-deploy
# https://github.com/marketplace/actions/deploy-to-heroku
name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  build:
    environment:
        name: production
        url: "https://k-bus-norikae-app.herokuapp.com/"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - uses: akhileshns/heroku-deploy@v3.12.12
      #   with:
      #     heroku_api_key: ${{secrets.HEROKU_API_KEY}}
      #     heroku_app_name: "k-bus-norikae-app"
      #     heroku_email: ${{secrets.HEROKU_EMAIL}}
      #     usedocker: true # https://github.com/marketplace/actions/deploy-to-heroku#deploy-with-docker
      - name: Login to Heroku Container registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          echo "Executing 'heroku container:login'"
          heroku container:login
      - name: Build and push
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          echo "Executing 'heroku container:push'"
          heroku container:push -a ${{ secrets.HEROKU_APP_NAME }} production --recursive
      - name: DB migrate
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          set -e
          echo "heroku config:set RAILS_ENV=production"
          heroku config:set RAILS_ENV=production \
            -a ${{ secrets.HEROKU_APP_NAME }}
          echo "heroku run bin/rails db:environment:set RAILS_ENV=production"
          heroku run bin/rails db:environment:set RAILS_ENV=production \
            -a ${{ secrets.HEROKU_APP_NAME }}
          echo "heroku run bundle exec bin/rails db:drop db:create db:migrate db:seed"
          heroku run bundle exec bin/rails db:create db:migrate db:seed \
            DISABLE_DATABASE_ENVIRONMENT_CHECK=1 \
            RAILS_ENV=production \
            bundle exec bin/rails db:create db:migrate db:seed \
            -a ${{ secrets.HEROKU_APP_NAME }}
          echo "heroku ps"
          heroku ps -a ${{ secrets.HEROKU_APP_NAME }}
      - name: Release
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          echo "Executing 'heroku container:release'"
          heroku container:release -a ${{ secrets.HEROKU_APP_NAME }} production
