# https://github.com/AkhileshNS/heroku-deploy
# https://github.com/marketplace/actions/deploy-to-heroku
name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  build:
    environment:
        name: production
        url: "https://k-bus-norikae-app.herokuapp.com/"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Heroku Container registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku container:login
      - name: Build and push
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku container:push -a ${{ secrets.HEROKU_APP_NAME }} production --recursive
      - name: Release
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku container:release -a ${{ secrets.HEROKU_APP_NAME }} production
      - name: DB migrate
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku run bundle exec bin/rails db:environment:set RAILS_ENV=production  -a ${{ secrets.HEROKU_APP_NAME }}
          heroku run bundle exec bin/rails db:create db:migrate db:seed DISABLE_DATABASE_ENVIRONMENT_CHECK=1 RAILS_ENV=production -a ${{ secrets.HEROKU_APP_NAME }}
      - name: Restart App
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku ps:restart -a ${{ secrets.HEROKU_APP_NAME }}
