# https://github.com/AkhileshNS/heroku-deploy
# https://github.com/marketplace/actions/deploy-to-heroku
name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  build:
    environment:
        name: production
        url: "https://k-bus-norikae-app.herokuapp.com/"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true # https://github.com/marketplace/actions/deploy-to-heroku#deploy-with-docker
          docker_build_args: |
            RAILS_ENV
        env:
          RAILS_ENV: production
