name: rspec

on:
  push:

jobs:
  rspec:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: run rspec
      run: |
        sudo docker-compose build
        sudo docker-compose up -d
        sudo docker-compose exec -T app rspec
